### ISSUE TITLE
Bad JavaScript code style

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [ArceusMatt/Dragon#6]
It's not a good style to write everything at the same indentation.

**Comment by ArceusMatt** [comment]
Of course it's not but this isn't exactly an issue either.
What do you expect from someone that doesn't code on a PC & mobile editors are horrible loading lots of lines of code? It runs & the syntax is correct that's all that matters. Another thing, i don't intend for people to read the code which is the reason i deleted the script itself from github.
